apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mall
    version: v1
  name: mall-v1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall
      version: v1
  template:
    metadata:
      labels:
        app: mall
        version: v1
    spec:
      containers:
      - image: zhongfox/simple-server
        imagePullPolicy: Always
        name: mall
        ports:
        - containerPort: 7777
          protocol: TCP
        - containerPort: 4444
          protocol: TCP
        env:
        - name: HTTP_PORT
          value: "7777"
        - name: TCP_PORT
          value: "4444"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mall
  name: mall
  namespace: demo
spec:
  ports:
  - name: http-m
    port: 7000
    protocol: TCP
    targetPort: 7777
  - name: tcp-m
    port: 4000
    protocol: TCP
    targetPort: 4444
  selector:
    app: mall
  type: ClusterIP
