apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: order
    version: v1
  name: order-v1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      containers:
      - image: zhongfox/simple-server
        imagePullPolicy: Always
        name: order
        ports:
        - containerPort: 7777
          protocol: TCP
        - containerPort: 4444
          protocol: TCP
        env:
        - name: HTTP_PORT
          value: "7777"
        - name: TCP_PORT
          value: "4444"
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: order
    version: v2
  name: order-v2
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v2
  template:
    metadata:
      labels:
        app: order
        version: v2
    spec:
      containers:
      - image: zhongfox/simple-server
        imagePullPolicy: Always
        name: order
        ports:
        - containerPort: 7777
          protocol: TCP
        - containerPort: 4444
          protocol: TCP
        env:
        - name: HTTP_PORT
          value: "7777"
        - name: TCP_PORT
          value: "4444"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
  namespace: demo
spec:
  ports:
  - name: http-o
    port: 7000
    protocol: TCP
    targetPort: 7777
  - name: tcp-o
    port: 4000
    protocol: TCP
    targetPort: 4444
  selector:
    app: order
  type: ClusterIP
